# Generated by Django 5.2.7 on 2025-10-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_force_udp_device_ommit_ping_device_password'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.device'),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='template',
            field=models.BinaryField(),
        ),
    ]
