# Generated by Django 5.2.7 on 2025-10-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_fingerprint_device_fingerprint_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id'], 'permissions': [('view_employee_section', 'Can access employee management section'), ('manage_employees', 'Can manage employee data'), ('manage_fingerprints', 'Can manage employee fingerprints')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
