# Generated by Django 5.2.7 on 2025-10-12 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connect', 'Connection Attempt'), ('test', 'Connection Test'), ('sync_employees_to', 'Sync Employees To Device'), ('sync_employees_from', 'Sync Employees From Device'), ('download_attendance', 'Download Attendance'), ('get_info', 'Get Device Info'), ('clear_attendance', 'Clear Attendance')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='device.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Log',
                'verbose_name_plural': 'Device Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='device_devi_timesta_3d0a2c_idx'), models.Index(fields=['device', '-timestamp'], name='device_devi_device__d72c3e_idx'), models.Index(fields=['status', '-timestamp'], name='device_devi_status_a3f375_idx'), models.Index(fields=['action', '-timestamp'], name='device_devi_action_6fb4e5_idx')],
            },
        ),
    ]
