# Generated by Django 5.2.7 on 2025-10-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='force_udp',
            field=models.BooleanField(default=False, help_text='Force UDP protocol instead of TCP'),
        ),
        migrations.AddField(
            model_name='device',
            name='ommit_ping',
            field=models.BooleanField(default=False, help_text='Skip ping test before connecting'),
        ),
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, help_text='Device communication password (optional)', max_length=50),
        ),
    ]
