# Generated by Django 5.2.7 on 2025-10-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_force_udp_device_ommit_ping_device_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at'], 'permissions': [('view_device_section', 'Can access device management section'), ('manage_devices', 'Can manage device configurations')], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
    ]
