# Generated by Django 5.2.7 on 2025-10-26 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_device_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=1, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Firmware Version'),
        ),
        migrations.AlterField(
            model_name='device',
            name='force_udp',
            field=models.BooleanField(default=False, help_text='Force UDP protocol instead of TCP', verbose_name='Force UDP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ommit_ping',
            field=models.BooleanField(default=False, help_text='Skip ping test before connecting', verbose_name='Omit Ping'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, help_text='Device communication password (optional)', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=4370, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='action',
            field=models.CharField(choices=[('connect', 'Connection Attempt'), ('test', 'Connection Test'), ('sync_employees_to', 'Sync Employees To Device'), ('sync_employees_from', 'Sync Employees From Device'), ('download_attendance', 'Download Attendance'), ('get_info', 'Get Device Info'), ('clear_attendance', 'Clear Attendance')], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='device.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Duration (seconds)'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('error', 'Error')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
