# Generated by Django 5.2.7 on 2025-10-26 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0005_alter_device_created_at_alter_device_device_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('sync_to_device', 'Sync To Device'), ('sync_from_device', 'Sync From Device'), ('download_attendance', 'Download Attendance'), ('upload_fingerprints', 'Upload Fingerprints'), ('download_fingerprints', 'Download Fingerprints')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='tasks_taskp_created_9e9a1f_idx'), models.Index(fields=['user', '-created_at'], name='tasks_taskp_user_id_8ebb8d_idx'), models.Index(fields=['status'], name='tasks_taskp_status_70f1d0_idx')],
            },
        ),
    ]
