# Generated by Django 5.2.7 on 2025-10-12 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('punch_type', models.IntegerField(choices=[(0, 'Check In'), (1, 'Check Out'), (2, 'Break Out'), (3, 'Break In'), (4, 'Overtime In'), (5, 'Overtime Out')], default=0)),
                ('verify_mode', models.IntegerField(default=0)),
                ('work_code', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Event',
                'verbose_name_plural': 'Attendance Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='attendance__timesta_0e2074_idx'), models.Index(fields=['employee', '-timestamp'], name='attendance__employe_4c9dda_idx')],
                'unique_together': {('device', 'user_id', 'timestamp')},
            },
        ),
    ]
