# Generated by Django 5.2.7 on 2025-10-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceevent',
            options={'ordering': ['-timestamp'], 'permissions': [('view_attendance_section', 'Can access attendance tracking section'), ('manage_attendance', 'Can manage attendance data'), ('download_attendance', 'Can download attendance from devices')], 'verbose_name': 'Attendance Event', 'verbose_name_plural': 'Attendance Events'},
        ),
    ]
